#pragma once

#define TO_STR(x) #x
#define STR(x) TO_STR(x)

#ifndef OCTO_PROJECT_NAME
#define OCTO_PROJECT_NAME "octo"
#endif

#ifndef OCTO_VERSION_MAJOR
#define OCTO_VERSION_MAJOR 0
#endif

#ifndef OCTO_VERSION_MINOR
#define OCTO_VERSION_MINOR 0
#endif

#ifndef OCTO_VERSION_PATCH
#define OCTO_VERSION_PATCH 0
#endif

#ifndef OCTO_VERSION
#define OCTO_VERSION STR(OCTO_VERSION_MAJOR) "." STR(OCTO_VERSION_MINOR) "." STR(OCTO_VERSION_PATCH)
#endif

#define OCTO_LOGGER_RESET "\033[0m"
#define OCTO_LOGGER_DEBUG "\033[2m"
#define OCTO_LOGGER_INFO "\033[1m"
#define OCTO_LOGGER_SYSTEM "\033[1;36m"
#define OCTO_LOGGER_WARN "\033[33m"
#define OCTO_LOGGER_ERROR "\033[31m"

#define OCTO_WINDOW_DEFAULT_TITLE OCTO_PROJECT_NAME " v" OCTO_VERSION
#define OCTO_WINDOW_DEFAULT_WIDTH 1280
#define OCTO_WINDOW_DEFAULT_HEIGHT 720
#define OCTO_WINDOW_DEFAULT_FULLSCREEN false

#define GLFW_INCLUDE_VULKAN

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
// #include <glm/vec4.hpp>
// #include <glm/mat4x4.hpp>
