#pragma once

#define TO_STR(x) #x
#define STR(x) TO_STR(x)

#ifndef OCTO_PRODUCT_NAME
#define OCTO_PRODUCT_NAME "octo"
#endif

#ifndef OCTO_VERSION_MAJOR
#define OCTO_VERSION_MAJOR 0
#endif

#ifndef OCTO_VERSION_MINOR
#define OCTO_VERSION_MINOR 0
#endif

#ifndef OCTO_VERSION_PATCH
#define OCTO_VERSION_PATCH 0
#endif

#ifndef OCTO_VERSION
#define OCTO_VERSION STR(OCTO_VERSION_MAJOR) "." STR(OCTO_VERSION_MINOR) "." STR(OCTO_VERSION_PATCH)
#endif

#ifndef OCTO_ENGINE_NAME_AND_VERSION
#define OCTO_ENGINE_NAME_AND_VERSION OCTO_PRODUCT_NAME " v" OCTO_VERSION
#endif

#if defined(OCTO_PLATFORM_WINDOWS)
#include <windows.h>
static bool win_console_initialized = false;
#endif

#define OCTO_VULKAN_API_VERSION VK_API_VERSION_1_3

// #define GLFW_CLIENT_NO_API
#define GLFW_INCLUDE_VULKAN

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_ENABLE_EXPERIMENTAL

// #define STB_IMAGE_IMPLEMENTATION
// #define TINYOBJLOADER_IMPLEMENTATION
