#pragma once

#define TO_STR(x) #x
#define STR(x) TO_STR(x)

#ifndef PRODUCT_NAME
#define PRODUCT_NAME "octo"
#endif

#ifndef VERSION_MAJOR
#define VERSION_MAJOR 0
#endif

#ifndef VERSION_MINOR
#define VERSION_MINOR 0
#endif

#ifndef VERSION_PATCH
#define VERSION_PATCH 0
#endif

#define ENGINE_NAME PRODUCT_NAME

#define OCTO_VERSION_MAJOR VERSION_MAJOR
#define OCTO_VERSION_MINOR VERSION_MINOR
#define OCTO_VERSION_PATCH VERSION_PATCH

#ifndef OCTO_VERSION
#define OCTO_VERSION STR(OCTO_VERSION_MAJOR) "." STR(OCTO_VERSION_MINOR) "." STR(OCTO_VERSION_PATCH)
#endif