#pragma once

#define TO_STR(x) #x
#define STR(x) TO_STR(x)

#define ENGINE_NAME PRODUCT_NAME

#define OCTO_VERSION_MAJOR VERSION_MAJOR
#define OCTO_VERSION_MINOR VERSION_MINOR
#define OCTO_VERSION_PATCH VERSION_PATCH

#ifndef OCTO_VERSION
#define OCTO_VERSION STR(OCTO_VERSION_MAJOR) "." STR(OCTO_VERSION_MINOR) "." STR(OCTO_VERSION_PATCH)
#endif