#pragma once


#if defined WIN32 || defined __MINGW32__
#define VK_USE_PLATFORM_WIN32_KHR
#define GLFW_EXPOSE_NATIVE_WIN32
#elif defined COCOA
#define VK_USE_PLATFORM_MACOS_MVK
#elif defined UIKIT
#define VK_USE_PLATFORM_IOS_MVK
#elif defined XCB
#define VK_USE_PLATFORM_XCB_KHR
#elif defined ANDROID
#define VK_USE_PLATFORM_ANDROID_KHR
#endif

#define GLFW_INCLUDE_VULKAN

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_ENABLE_EXPERIMENTAL

// #define GLM_FORCE_SSE42 1
// #define GLM_FORCE_DEFAULT_ALIGNED_GENTYPES 1
