#pragma once

#include "version.hpp"

// #define GLFW_INCLUDE_VULKAN
#define GLFW_CLIENT_NO_API

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#define GLM_ENABLE_EXPERIMENTAL

#define STB_IMAGE_IMPLEMENTATION

#define TINYOBJLOADER_IMPLEMENTATION
