#define OCTO_GAMEPAD_AXIS_LEFT_X 0
#define OCTO_GAMEPAD_AXIS_LEFT_Y 1
#define OCTO_GAMEPAD_AXIS_RIGHT_X 2
#define OCTO_GAMEPAD_AXIS_RIGHT_Y 3
#define OCTO_GAMEPAD_AXIS_LEFT_TRIGGER 4
#define OCTO_GAMEPAD_AXIS_RIGHT_TRIGGER 5
#define OCTO_GAMEPAD_AXIS_LAST OCTO_GAMEPAD_AXIS_RIGHT_TRIGGER

#define OCTO_GAMEPAD_BUTTON_A 0
#define OCTO_GAMEPAD_BUTTON_B 1
#define OCTO_GAMEPAD_BUTTON_X 2
#define OCTO_GAMEPAD_BUTTON_Y 3
#define OCTO_GAMEPAD_BUTTON_LEFT_BUMPER 4
#define OCTO_GAMEPAD_BUTTON_RIGHT_BUMPER 5
#define OCTO_GAMEPAD_BUTTON_BACK 6
#define OCTO_GAMEPAD_BUTTON_START 7
#define OCTO_GAMEPAD_BUTTON_GUIDE 8
#define OCTO_GAMEPAD_BUTTON_LEFT_THUMB 9
#define OCTO_GAMEPAD_BUTTON_RIGHT_THUMB 10
#define OCTO_GAMEPAD_BUTTON_DPAD_UP 11
#define OCTO_GAMEPAD_BUTTON_DPAD_RIGHT 12
#define OCTO_GAMEPAD_BUTTON_DPAD_DOWN 13
#define OCTO_GAMEPAD_BUTTON_DPAD_LEFT 14
#define OCTO_GAMEPAD_BUTTON_LAST OCTO_GAMEPAD_BUTTON_DPAD_LEFT
#define OCTO_GAMEPAD_BUTTON_CROSS OCTO_GAMEPAD_BUTTON_A
#define OCTO_GAMEPAD_BUTTON_CIRCLE OCTO_GAMEPAD_BUTTON_B
#define OCTO_GAMEPAD_BUTTON_SQUARE OCTO_GAMEPAD_BUTTON_X
#define OCTO_GAMEPAD_BUTTON_TRIANGLE OCTO_GAMEPAD_BUTTON_Y

#define OCTO_JOYSTICK_1 0
#define OCTO_JOYSTICK_2 1
#define OCTO_JOYSTICK_3 2
#define OCTO_JOYSTICK_4 3
#define OCTO_JOYSTICK_5 4
#define OCTO_JOYSTICK_6 5
#define OCTO_JOYSTICK_7 6
#define OCTO_JOYSTICK_8 7
#define OCTO_JOYSTICK_9 8
#define OCTO_JOYSTICK_10 9
#define OCTO_JOYSTICK_11 10
#define OCTO_JOYSTICK_12 11
#define OCTO_JOYSTICK_13 12
#define OCTO_JOYSTICK_14 13
#define OCTO_JOYSTICK_15 14
#define OCTO_JOYSTICK_16 15
#define OCTO_JOYSTICK_LAST OCTO_JOYSTICK_16

#define OCTO_HAT_CENTERED 0
#define OCTO_HAT_UP 1
#define OCTO_HAT_RIGHT 2
#define OCTO_HAT_DOWN 4
#define OCTO_HAT_LEFT 8
#define OCTO_HAT_RIGHT_UP (OCTO_HAT_RIGHT | OCTO_HAT_UP)
#define OCTO_HAT_RIGHT_DOWN (OCTO_HAT_RIGHT | OCTO_HAT_DOWN)
#define OCTO_HAT_LEFT_UP (OCTO_HAT_LEFT | OCTO_HAT_UP)
#define OCTO_HAT_LEFT_DOWN (OCTO_HAT_LEFT | OCTO_HAT_DOWN)
